// Open and Save PDF in Azure Blob Storage using Standalone/AngularClient/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { PdfViewerModule, LinkAnnotationService, BookmarkViewService,
         MagnificationService, ThumbnailViewService, ToolbarService,
         NavigationService, TextSearchService, TextSelectionService,
         PrintService, FormDesignerService, FormFieldsService, 
         AnnotationService, PageOrganizerService, CustomToolbarItemModel } from '@syncfusion/ej2-angular-pdfviewer';
import { BlockBlobClient } from "@azure/storage-blob";

@Component({
  selector: 'app-root',
  // specifies the template string for the PDF Viewer component
  template: `<div class="content-wrapper">
                <ejs-pdfviewer id="pdfViewer"
                    [resourceUrl]='resource' 
                    [toolbarSettings]="toolbarSettings"
                    (toolbarClick)="toolbarClick($event)"
                    (created)='LoadPdfFromBlob()'
                    style="height:640px;display:block">
                </ejs-pdfviewer>
             </div>`,
  providers: [ LinkAnnotationService, BookmarkViewService, MagnificationService,
               ThumbnailViewService, ToolbarService, NavigationService,
               TextSearchService, TextSelectionService, PrintService,
               AnnotationService, FormDesignerService, FormFieldsService, PageOrganizerService]
})
export class AppComponent implements OnInit {
  public resource: string = "https://cdn.syncfusion.com/ej2/23.1.43/dist/ej2-pdfviewer-lib";

  public toolItem1: CustomToolbarItemModel = {
    prefixIcon: 'e-icons e-pv-download-document-icon',
    id: 'download_pdf',
    tooltipText: 'Download file',
    align: 'right'
  };

  public toolbarSettings = {
    showTooltip: true,
    toolbarItems: ['OpenOption', 'PageNavigationTool', 'MagnificationTool', 'PanTool', 'SelectionTool', 'SearchOption', 'PrintOption', this.toolItem1, 'UndoRedoTool', 'AnnotationEditTool', 'FormDesignerEditTool', 'CommentTool', 'SubmitForm']
  };

  public toolbarClick(args: any): void {
    if (args.item && args.item.id === 'download_pdf') {
      this.SavePdfToBlob();
    }
  }

  ngOnInit(): void {
  }

  private accountName: string = "openpdfazure";
  private containerName: string = "fileupload";
  private blobName: string = "PDF_Succinctly.pdf";
  private SASUrl: string = "https://openpdfazure.blob.core.windows.net/fileupload/PDF_Succinctly.pdf?sp=racwdyti&st=2024-07-04T05:44:04Z&se=2024-07-11T13:44:04Z&spr=https&sv=2022-11-02&sr=b&sig=b0nGmZcXFBEJRHGmgUfcoxTLtuw8CIlCGgPjuDTQj3Y%3D";

  LoadPdfFromBlob() {
    const url = 'https://'+this.accountName+'.blob.core.windows.net/'+this.containerName+'/'+this.blobName;
    this.fetchAndConvertToBase64(url).then(base64String => {
      if (base64String) {
          var viewer = (<any>document.getElementById("pdfViewer")).ej2_instances[0];  
          setTimeout(() => {
            viewer.load("data:application/pdf;base64,"+base64String);
          }, 2000);
      } else {
          console.error('Failed to fetch and convert file to base64.');
      }
    }).catch(error => console.error('Error:', error));
  }

  async fetchAndConvertToBase64(url: string): Promise<string | null> {
    try {
      const response = await fetch(url);
      if (!response.ok) {
        throw new Error(`HTTP error! Status: ${response.status}`);
      }

      const blob = await response.blob();
      const base64String = await this.blobToBase64(blob);
      return base64String;
    } catch (error) {
      console.error('Error fetching file:', error);
      return null;
    }
  }

  blobToBase64(blob: Blob): Promise<string> {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => {
          const base64String = reader.result?.toString().split(',')[1] || '';
          resolve(base64String);
      };
      reader.onerror = error => reject(error);
      reader.readAsDataURL(blob);
    });
  }

  SavePdfToBlob() {
    var proxy = this;
    var pdfViewer = (<any>document.getElementById('pdfViewer')).ej2_instances[0];
    pdfViewer.saveAsBlob().then(function (value: Blob) {
      var reader = new FileReader();
      reader.onload = async () => {
        // Convert ArrayBuffer to Uint8Array
        if (reader.result) {
          const arrayBuffer = reader.result as ArrayBuffer;
          const blobClient = new BlockBlobClient(proxy.SASUrl);
          // Upload data to the blob
          const uploadBlobResponse = await blobClient.upload(arrayBuffer, arrayBuffer.byteLength);
          console.log(`Upload blob successfully`, uploadBlobResponse.requestId);
        }
      };
      reader.readAsArrayBuffer(value);
    });
  }
}

// Open and Save PDF in Azure Blob Storage using Standalone/VuejsClient/src/App.vue
<template>
  <ejs-pdfviewer 
    id="pdfViewer" 
    :resourceUrl="resourceUrl" 
    :toolbarClick="toolbarClick" 
    :created="loadPdfDocument" 
    :toolbarSettings="toolbarSettings">
  </ejs-pdfviewer>
</template>

<script>
import { PdfViewerComponent, Toolbar, Magnification, Navigation, LinkAnnotation, BookmarkView, 
           ThumbnailView, Print, TextSelection, TextSearch, Annotation, FormDesigner, FormFields, PageOrganizer } from '@syncfusion/ej2-vue-pdfviewer';
import { BlockBlobClient } from "@azure/storage-blob";

  export default {
    name: 'App',

    components: {
      "ejs-pdfviewer": PdfViewerComponent
    },

    data() {
      let toolItem1 = {
        prefixIcon: 'e-icons e-pv-download-document-icon',
        id: 'download_pdf',
        tooltipText: 'Download file',
        align: 'right'
      };

      return {
        resourceUrl: 'https://cdn.syncfusion.com/ej2/23.1.43/dist/ej2-pdfviewer-lib',
        toolbarSettings: {
          toolbarItems: [ 'OpenOption', 'PageNavigationTool', 'MagnificationTool', 'PanTool', 'SelectionTool', 'SearchOption', 'PrintOption', toolItem1, 'UndoRedoTool', 'AnnotationEditTool', 'FormDesignerEditTool', 'CommentTool', 'SubmitForm']
        },
      };
    },

    methods: {
      toolbarClick: function (args) {
          if (args.item && args.item.id === 'download_pdf') {
            this.savePdfDocument();
          }
      },

      loadPdfDocument: async function () {
        var SASUrl = "*Your SAS Url in Azure*";
        const response = await fetch(SASUrl);
        const arrayBuffer = await response.arrayBuffer();
        const uint8Array = new Uint8Array(arrayBuffer);
        const base64String = btoa(
          String.fromCharCode(...uint8Array)
        );
        var viewer = document.getElementById('pdfViewer').ej2_instances[0];
        setTimeout(function() {
          viewer.load("data:application/pdf;base64," + base64String);
        }, 2000);
      },

      savePdfDocument: function () {
        var viewer = document.getElementById('pdfViewer').ej2_instances[0];
        viewer.saveAsBlob().then(function (value) {
          var reader = new FileReader();
          reader.onload = async () => {
            if (reader.result) {
              var SASUrl = "*Your SAS Url in Azure*";
              const arrayBuffer = reader.result;
              const blobClient = new BlockBlobClient(SASUrl);
              const uploadBlobResponse = await blobClient.upload(arrayBuffer, arrayBuffer.byteLength);
              console.log(`Upload blob successfully`, uploadBlobResponse.requestId);
            }
          };
          reader.readAsArrayBuffer(value);
        });
      }
    },

    provide: {
      PdfViewer: [ Toolbar, Magnification, Navigation, LinkAnnotation, BookmarkView, ThumbnailView,
                   Print, TextSelection, TextSearch, Annotation, FormDesigner, FormFields, PageOrganizer ]
    }
  }
</script>

<style>
  @import '../node_modules/@syncfusion/ej2-base/styles/material.css';
  @import '../node_modules/@syncfusion/ej2-buttons/styles/material.css';
  @import '../node_modules/@syncfusion/ej2-dropdowns/styles/material.css';  
  @import '../node_modules/@syncfusion/ej2-inputs/styles/material.css';  
  @import '../node_modules/@syncfusion/ej2-navigations/styles/material.css';
  @import '../node_modules/@syncfusion/ej2-popups/styles/material.css';
  @import '../node_modules/@syncfusion/ej2-splitbuttons/styles/material.css';
  @import '../node_modules/@syncfusion/ej2-lists/styles/material.css';
  @import '../node_modules/@syncfusion/ej2-vue-pdfviewer/styles/material.css';
</style>
